### ISSUE TITLE
NoSuchMethodError: AbstractGoogleJsonClient$Builder.setBatchPath

### ISSUE THREAD

**Issue by slakr** [GoogleCloudPlatform/getting-started-java#325] opened 2017-11-15 21:35 UTC
Looks like this is from recent version bump of google.cloud.storage version to 1.10.0 which is relying on a newer version of client libs. Version bump on google-api-client-appengine seems to fix it, patch to follow.

Full error stack: 

[INFO] java.lang.NoSuchMethodError: com.google.api.client.googleapis.services.json.AbstractGoogleJsonClient$Builder.setBatchPath(Ljava/lang/String;)Lcom/google/api/client/googleapis/services/AbstractGoogleClient$Builder;
[INFO] 	at com.google.api.services.storage.Storage$Builder.setBatchPath(Storage.java:9263)
[INFO] 	at com.google.api.services.storage.Storage$Builder.<init>(Storage.java:9242)
[INFO] 	at com.google.cloud.storage.spi.v1.HttpStorageRpc.<init>(HttpStorageRpc.java:92)
[INFO] 	at com.google.cloud.storage.StorageOptions$DefaultStorageRpcFactory.create(StorageOptions.java:53)
[INFO] 	at com.google.cloud.storage.StorageOptions$DefaultStorageRpcFactory.create(StorageOptions.java:47)
[INFO] 	at com.google.cloud.ServiceOptions.getRpc(ServiceOptions.java:472)
[INFO] 	at com.google.cloud.storage.StorageOptions.getStorageRpcV1(StorageOptions.java:121)
[INFO] 	at com.google.cloud.storage.StorageImpl.<init>(StorageImpl.java:99)
[INFO] 	at com.google.cloud.storage.StorageOptions$DefaultStorageFactory.create(StorageOptions.java:43)
[INFO] 	at com.google.cloud.storage.StorageOptions$DefaultStorageFactory.create(StorageOptions.java:37)
[INFO] 	at com.google.cloud.ServiceOptions.getService(ServiceOptions.java:459)
[INFO] 	at com.example.getstarted.util.CloudStorageHelper.<clinit>(CloudStorageHelper.java:45)
[INFO] 	at com.example.getstarted.basicactions.ListBookServlet.init(ListBookServlet.java:45)
[INFO] 	at javax.servlet.GenericServlet.init(GenericServlet.java:212)
[INFO] 	at org.mortbay.jetty.servlet.ServletHolder.initServlet(ServletHolder.java:440)
[INFO] 	at org.mortbay.jetty.servlet.ServletHolder.doStart(ServletHolder.java:263)

**Comment by Kryword** [comment] 2018-01-03 20:46
There should be a version bump on of google-api-client-appengine to 1.23.0 on the 4-auth version too.

**Comment by prmdsharma-off** [comment] 2018-02-27 06:58
Issue Still persist.

nested exception is java.lang.NoSuchMethodError: com.google.api.client.googleapis.services.json.AbstractGoogleJsonClient$Builder.setBatchPath(Ljava/lang/String;)Lcom/google/api/client/googleapis/services/AbstractGoogleClient$Builder;
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.instantiateBean(AbstractAutowireCapableBeanFactory.java:1155) ~[spring-beans-4.3.6.RELEASE.jar:4.3.6.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1099) ~[spring-beans-4.3.6.RELEASE.jar:4.3.6.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:513) ~[spring-beans-4.3.6.RELEASE.jar:4.3.6.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:483) ~[spring-beans-4.3.6.RELEASE.jar:4.3.6.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:306) ~[spring-beans-4.3.6.RELEASE.jar:4.3.6.RELEASE]
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:230) ~[spring-beans-4.3.6.RELEASE.jar:4.3.6.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:302) ~[spring-beans-4.3.6.RELEASE.jar:4.3.6.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:197) ~[spring-beans-4.3.6.RELEASE.jar:4.3.6.RELEASE]
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:761) ~[spring-beans-4.3.6.RELEASE.jar:4.3.6.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:866) ~[spring-context-4.3.6.RELEASE.jar:4.3.6.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:542) ~[spring-context-4.3.6.RELEASE.jar:4.3.6.RELEASE]
	at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.refresh(EmbeddedWebApplicationContext.java:122) ~[spring-boot-1.4.4.RELEASE.jar:1.4.4.RELEASE]
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:762) ~[spring-boot-1.4.4.RELEASE.jar:1.4.4.RELEASE]
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:372) ~[spring-boot-1.4.4.RELEASE.jar:1.4.4.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:316) ~[spring-boot-1.4.4.RELEASE.jar:1.4.4.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1187) ~[spring-boot-1.4.4.RELEASE.jar:1.4.4.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1176) ~[spring-boot-1.4.4.RELEASE.jar:1.4.4.RELEASE]
	at com.ofb.web.Application.main(Application.java:230) ~[classes/:?]
Caused by: org.springframework.beans.BeanInstantiationException: Failed to instantiate [com.ofb.libs.service.GCMService]: Constructor threw exception; nested exception is java.lang.NoSuchMethodError: com.google.api.client.googleapis.services.json.AbstractGoogleJsonClient$Builder.setBatchPath(Ljava/lang/String;)Lcom/google/api/client/googleapis/services/AbstractGoogleClient$Builder;
	at org.springframework.beans.BeanUtils.instantiateClass(BeanUtils.java:154) ~[spring-beans-4.3.6.RELEASE.jar:4.3.6.RELEASE]
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:89) ~[spring-beans-4.3.6.RELEASE.jar:4.3.6.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.instantiateBean(AbstractAutowireCapableBeanFactory.java:1147) ~[spring-beans-4.3.6.RELEASE.jar:4.3.6.RELEASE]
	... 17 more
Caused by: java.lang.NoSuchMethodError: com.google.api.client.googleapis.services.json.AbstractGoogleJsonClient$Builder.setBatchPath(Ljava/lang/String;)Lcom/google/api/client/googleapis/services/AbstractGoogleClient$Builder;
	at com.google.api.services.storage.Storage$Builder.setBatchPath(Storage.java:9263) ~[google-api-services-storage-v1-rev114-1.23.0.jar:?]

**Comment by prmdsharma-off** [comment] 2018-02-27 06:59
any work around ??

**Comment by GoldsoftInc** [comment] 2018-03-28 09:14
Something like this occurred when I was running an Android app. I was able to run it successfully after updating my dependencies:

compile 'com.google.api-client:google-api-client:1.23.0'
compile 'com.google.http-client:google-http-client-android:1.23.0'

**Comment by aleksgorbenko** [comment] 2018-03-29 09:05
Had this issue when trying to query `https://www.googleapis.com/auth/userinfo` endpoint using `com.google.oauth-client:google-oauth-client:1.23.0`, updating the following dependencies solved the issue:

```
com.google.api-client:google-api-client:1.23.0
com.google.http-client:google-http-client-jackson2:1.23.0
com.google.http-client:google-http-client:1.23.0
```

**Comment by maitl** [comment] 2018-04-06 09:46
I have the same issue trying to use V2 Endpoints and google-api-client:1.23.0

**Comment by nilsonpontello** [comment] 2018-04-28 13:27
You must make a clean build after changing from 1.22.0 to 1.23.0 otherwise old libs will still be used, specially if you are generating **war** files using **maven**.

**Comment by lohithnagaroor** [comment] 2019-07-12 05:14
Initially i too had same issue for accessing GA V2 endpoints. Please update this below dependencies to  access V3 

<dependency>
            <groupId>com.google.api-client</groupId>
            <artifactId>google-api-client</artifactId>
            <version>1.23.1</version>
            <exclusions>
                <exclusion>
                    <groupId>com.google.guava</groupId>
                    <artifactId>guava-jdk5</artifactId>
                </exclusion>
            </exclusions>
        </dependency>
and 
<dependency>
            <groupId>com.google.apis</groupId>
            <artifactId>google-api-services-analytics</artifactId>
            <version>v3-rev161-1.25.0</version>
        </dependency>

**Comment by liufuyang** [comment] 2019-07-30 15:00
I seem to have to use something like these to fix the issue:
```
        <dependency>
            <groupId>com.google.http-client</groupId>
            <artifactId>google-http-client</artifactId>
            <version>1.25.0</version>
        </dependency>
        <dependency>
            <groupId>com.google.http-client</groupId>
            <artifactId>google-http-client-jackson2</artifactId>
            <version>1.25.0</version>
        </dependency>
        <dependency>
            <groupId>com.google.apis</groupId>
            <artifactId>google-api-services-storage</artifactId>
            <version>v1-rev158-1.25.0</version>
        </dependency>
```
Note the last `v1-rev158-1.25.0` is needed for the storage version

**Comment by theferrit32** [comment] 2019-08-14 00:27
I had a NoSuchMethodError on a different method but with a similar sort of stack trace. I updated all the `com.google.*` dependencies to latest versions and made sure the version numbers matched and it works now.

**Comment by dzlier-gcp** [comment] 2019-10-14 19:02
I will look at getting the Auto Update Dependencies PR merged, that should resolve this issue upon first cloning the repo.

**Comment by volcanicprateek** [comment] 2019-11-16 13:48
Is this resolved? I am still getting this issue 

I used this in my pom.xml:
```
<dependency>
            <groupId>com.google.apis</groupId>
            <artifactId>google-api-services-sheets</artifactId>
            <version>v4-rev581-1.25.0</version>
        </dependency>
        <dependency>
            <groupId>com.google.api-client</groupId>
            <artifactId>google-api-client</artifactId>
            <version>1.25.0</version>
        </dependency>
        <dependency>
            <groupId>com.google.oauth-client</groupId>
            <artifactId>google-oauth-client-jetty</artifactId>
            <version>1.23.0</version>
        </dependency>
        <dependency>
            <groupId>com.google.http-client</groupId>
            <artifactId>google-http-client</artifactId>
            <version>1.25.0</version>
        </dependency>
        <dependency>
            <groupId>com.google.http-client</groupId>
            <artifactId>google-http-client-jackson2</artifactId>
            <version>1.25.0</version>
        </dependency>
```

**Comment by sshevlyagin** [comment] 2020-02-14 16:05
Potential solution on [stackoverflow](https://stackoverflow.com/a/60229761/305466)

**Closed** 2020-12-09 23:12 UTC
Labels: priority: p2

**Comment by leenabhandari** [comment] 2022-04-24 06:37
> I seem to have to use something like these to fix the issue:
> 
> ```
>         <dependency>
>             <groupId>com.google.http-client</groupId>
>             <artifactId>google-http-client</artifactId>
>             <version>1.25.0</version>
>         </dependency>
>         <dependency>
>             <groupId>com.google.http-client</groupId>
>             <artifactId>google-http-client-jackson2</artifactId>
>             <version>1.25.0</version>
>         </dependency>
>         <dependency>
>             <groupId>com.google.apis</groupId>
>             <artifactId>google-api-services-storage</artifactId>
>             <version>v1-rev158-1.25.0</version>
>         </dependency>
> ```
> 
> Note the last `v1-rev158-1.25.0` is needed for the storage version

this worked for me
