### ISSUE TITLE
NoSuchMethodError: com.google.common.io.ByteStreams.exhaust(Ljava/io/InputStream;)J

### ISSUE THREAD

**Issue by beena-yatin-kanyal** [GoogleCloudPlatform/getting-started-java#1090] opened 2021-10-25 12:38 UTC
We are using some Google cloud dependencies in our rest-assured project and suddenly they have started to break due to the below error. Can anyone please take a look and advice?

**IDE** - IntelliJ
**Gradle** - 7.0

**Error -**
```
java.lang.NoSuchMethodError: com.google.common.io.ByteStreams.exhaust(Ljava/io/InputStream;)J

	at com.google.api.client.http.ConsumingInputStream.close(ConsumingInputStream.java:40)
	at java.util.zip.InflaterInputStream.close(InflaterInputStream.java:227)
	at java.util.zip.GZIPInputStream.close(GZIPInputStream.java:136)
	at com.fasterxml.jackson.core.json.UTF8StreamJsonParser._closeInput(UTF8StreamJsonParser.java:252)
	at com.fasterxml.jackson.core.base.ParserBase.close(ParserBase.java:369)
	at com.google.api.client.json.jackson2.JacksonParser.close(JacksonParser.java:50)
	at com.google.api.client.json.JsonParser.parse(JsonParser.java:363)
	at com.google.api.client.json.JsonParser.parse(JsonParser.java:335)
	at com.google.api.client.json.JsonObjectParser.parseAndClose(JsonObjectParser.java:79)
	at com.google.api.client.json.JsonObjectParser.parseAndClose(JsonObjectParser.java:73)
	at com.google.api.client.http.HttpResponse.parseAs(HttpResponse.java:451)
	at com.google.auth.oauth2.ServiceAccountCredentials.refreshAccessToken(ServiceAccountCredentials.java:447)
	at com.google.auth.oauth2.OAuth2Credentials.refresh(OAuth2Credentials.java:157)
	at com.google.auth.oauth2.OAuth2Credentials.getRequestMetadata(OAuth2Credentials.java:145)
	at com.google.auth.oauth2.ServiceAccountCredentials.getRequestMetadata(ServiceAccountCredentials.java:603)
	at com.google.auth.http.HttpCredentialsAdapter.initialize(HttpCredentialsAdapter.java:91)
	at com.google.cloud.http.HttpTransportOptions$1.initialize(HttpTransportOptions.java:159)
	at com.google.cloud.http.CensusHttpModule$CensusHttpRequestInitializer.initialize(CensusHttpModule.java:109)
	at com.google.cloud.datastore.spi.v1.HttpDatastoreRpc$1.initialize(HttpDatastoreRpc.java:91)
	at com.google.datastore.v1.client.RemoteRpc.call(RemoteRpc.java:91)
	at com.google.datastore.v1.client.Datastore.lookup(Datastore.java:95)
	at com.google.cloud.datastore.spi.v1.HttpDatastoreRpc.lookup(HttpDatastoreRpc.java:171)
	at com.google.cloud.datastore.DatastoreImpl$3.call(DatastoreImpl.java:416)
	at com.google.cloud.datastore.DatastoreImpl$3.call(DatastoreImpl.java:413)
	at com.google.api.gax.retrying.DirectRetryingExecutor.submit(DirectRetryingExecutor.java:105)
	at com.google.cloud.RetryHelper.run(RetryHelper.java:76)
	at com.google.cloud.RetryHelper.runWithRetries(RetryHelper.java:50)
	at com.google.cloud.datastore.DatastoreImpl.lookup(DatastoreImpl.java:412)
	at com.google.cloud.datastore.DatastoreImpl$ResultsIterator.loadResults(DatastoreImpl.java:387)
	at com.google.cloud.datastore.DatastoreImpl$ResultsIterator.<init>(DatastoreImpl.java:383)
	at com.google.cloud.datastore.DatastoreImpl.get(DatastoreImpl.java:373)
	at com.google.cloud.datastore.DatastoreImpl.get(DatastoreImpl.java:336)
	at com.google.cloud.datastore.DatastoreHelper.get(DatastoreHelper.java:45)
	at com.google.cloud.datastore.DatastoreImpl.get(DatastoreImpl.java:321)
```

**Dependencies -**
```
dependencies {
	compile(group: 'com.jayway.jsonpath', name: 'json-path', version: '2.0.0')
	compile group: 'io.jsonwebtoken', name: 'jjwt', version: '0.9.1'
//see https://mvnrepository.com/artifact/com.google.cloud/libraries-bom/11.1.0
	compile group: 'com.google.auth', name: 'google-auth-library-oauth2-http', version: '0.21.1'//Jul, 2020
	compile group: 'com.google.cloud', name: 'google-cloud-datastore', version: '1.105.0'//(Sep, 2020)
	compile group: 'com.google.cloud', name: 'google-cloud-storage', version: '1.113.1'//Sep, 2020
	compile group: 'com.google.cloud', name: 'google-cloud-pubsub', version: '1.108.1' //Aug, 2020
	compile group: 'com.google.cloud', name: 'google-cloud-bigquery', version: '1.120.0' //Sep, 2020
}

configurations.all {
	resolutionStrategy {
		force 'com.google.protobuf:protobuf-java:3.13.0'
		force 'com.google.api-client:google-api-client:1.30.11' //Oct, 2020
	}
}
```

**Comment by beena-yatin-kanyal** [comment] 2021-10-30 03:31
[1] - I am running the setup on the windows environment. here is the quick snippet of I am running this code -
![image](https://user-images.githubusercontent.com/46935197/139517966-4085f086-9ec6-44d6-a8d4-ac0a89d21b07.png)

[2] - I gave a thought to your suggestion in the second comment and it is really a strange thing. I am a little surprised that nowhere I find the pre-20 guava dependency both at runtime and compile time. secondly, there were conflicts constraints (i.e. `+--- com.google.guava:guava:30.1.1-jre -> 21.0 (c)` but pre-20 guava was no nowhere). I am not sure from where it is picking up during the runtime run and messing up the whole dev environment.

**Comment by chanseokoh** [comment] 2021-11-01 15:19
Never heard of TestNG, but based on my quick search, I'll assume that it's just another test framework for unit tests that is very similar to JUnit and can be substituted for JUnit. (If it does something more than that, or it can fork a JVM process to launch your test code, or you set up your project to do so, etc., then the following arguments may not apply verbatim.)

In any case, I think this is just your local environment and configuration issue.

- For compiling _test_ source code and running the compiled _tests_, you should check the dependency trees of test compile classpath and the test runtime classpath. Look for `testCompileClasspath` and `testRuntimeClasspath` from the output of `./gradlew dependencies` (for your sub-module). However, I don't really think there's an issue in the test classpaths, since you said it works fine on Jenkins. And make sure you are using the exact same code on Jenkins and your local machine.

- For troubleshooting, don't run TestNG inside IDE but on the command-line. IDEs and IDE plugins maintain its own classpaths, so it just adds another layer of complexity. There's a good chance that it works on the command-line but not inside IDE. Your goal is to make the command-line work and verify it.

- If running tests on the command-line still doesn't work, all I can think of is that TestNG does not correctly run your test code with the right set of test runtime classpath or somehow it interferes with it. You should seek help from the TestNG community.

**Comment by beena-yatin-kanyal** [comment] 2021-11-01 16:09
@chanseokoh - It is something similar to the selenium framework and yes understanding is correct about the TestNG framework (_sort of an automation suite_). please find my answers below -

[1] - yes the code is the same. I just tried the git pull origin some_branch and no updates were received.
[2] - I am not sure if it will be a good idea but I will try just to check if something new comes up
[3] - I don't think it is an issue with the TestNG setup as the community will be responsible for their issues, not the ones triggered by google libs. Sorry to say but the libs have messed up by already working environment and now the same issue has started to haunt not just one by multiple developers.

I have cleared the entire Gradle cache from my system and let us see (*fingers crosses*). hopefully, it should work as it will be redownloading all jars (specified in the project) again.

**Comment by chanseokoh** [comment] 2021-11-01 16:35
I think you have a misunderstanding on the nature of this issue. I am spending my own time to debug your own personal project setup issue out of my curiosity and also as a good citizen. I don't see any evidence that this is an issue caused by Google libs. In my perspective, evidence is pointing to that you (your project setup, environment, configuration, TestNG framework, and what not) are not just correctly using the test runtime classpath. So, all you have to do is to do so.

**Comment by beena-yatin-kanyal** [comment] 2021-11-01 17:03
thanks and I appreciate it @chanseokoh and apologies if my comment was a bit rude. anyways coming back to the issue. I am not sure if I am correct but no matter whichever version of google lib I download the guava always remains 21 (_ I think this is internal to how the jar is bonded_)?

![image](https://user-images.githubusercontent.com/46935197/139709492-5f9bc430-4126-46a1-a03c-82d99c5bf499.png)

This is not something I am putting it manually. let me see what else I can go now. once again thanks.

**Comment by chanseokoh** [comment] 2021-11-01 17:25
No worries, nothing to apologize. Sorry if you felt that way :sweat_smile:

That datastore may define the Guava 21 dependency, but don't be too obsessed with it. Because, whether using Maven or Guava, in the end, you can always enforce whatever Guava version you want to use in your project. (And this is what you are actually doing, as v21 is being forced as a dependency constraint, and in https://github.com/GoogleCloudPlatform/getting-started-java/issues/1090#issuecomment-954797667 you were able to do so.) If you ask how you are supposed to know which Guava version is the best one to use with all GCP libraries, the best way would be to use the libraries BOM (probably with `enforcedPlatform()`). However, for now, you should just focus on resolving the issue.

That said, even if it's using Guava 21, I don't think that is a problem for the issue, because v21 does have the method of our interest as I said.

As long as the dependency trees that Gradle reports is correct, you should be good. (There is a case that Gradle may report a wrong tree, but I don't think it applies here.) The fact that it also works on Jenkins makes me believe that there are difference at runtime somehow. I emphasize again that for troubleshooting, work on the command-line first while excluding IDE. And I think there's also a possibility that the TestNG framework (or the way you set it up) is playing a role.

**Comment by chanseokoh** [comment] 2021-11-01 17:53
But to answer your question

> no matter whichever version of google lib I download the guava always remains 21 (_ I think this is internal to how the jar is bonded_)?

No. `datastore` declares Guava 21. Check the following log as an example.

```
~$ cd /tmp
/tmp$ mkdir a
/tmp/a$ cd a
/tmp/a$ cat > build.gradle <<EOL
plugins { id 'java' }
repositories { mavenCentral() }
dependencies { implementation 'com.google.cloud:google-cloud-datastore:2.1.3' }
EOL
/tmp/a$ gradle dependencies --configuration runtimeClasspath

> Task :dependencies

------------------------------------------------------------
Root project 'a'
------------------------------------------------------------

runtimeClasspath - Runtime classpath of source set 'main'.
\--- com.google.cloud:google-cloud-datastore:2.1.3
     ...
     +--- com.google.api:gax:2.6.1
     +--- com.google.guava:guava:31.0.1-jre
     +--- com.google.guava:failureaccess:1.0.1
     +--- com.google.guava:listenablefuture:9999.0-empty-to-avoid-conflict-with-guava
     +--- org.checkerframework:checker-qual:3.12.0
     ...
```

As I said, it is you (your project setup) that pins the Guava version to v21.

**Comment by chanseokoh** [comment] 2021-11-01 17:55
> datastore declares Guava 21

Sorry, I mean Guava 31.

**Comment by beena-yatin-kanyal** [comment] 2021-11-02 04:55
@chanseokoh - is there any dependency tree/UI that can help find which library is compatible with which? I cleared the entire cache just to be sure that there is no guava-21 lib in the system.

[1] - cleared the entire Gradle cache
[2] - redownloaded the Gradle libs with the new version. worked no guava21 lib.
[3] - failed with a new error - `java.lang.NoSuchMethodError: com.google.api.client.http.HttpTransport.isMtls()Z`

* dependency tree with latest google libs * (even forced a few just to be sure)
```
dependencies {
    frameworkJars('com.myoffice.automation:APICore:1.0.0') {
        transitive = false
    }
    implementation(group: 'com.jayway.jsonpath', name: 'json-path', version: '2.0.0')
    implementation(group: 'io.jsonwebtoken', name: 'jjwt', version: '0.9.1')
    implementation(group: 'com.google.auth', name: 'google-auth-library-oauth2-http',
            version: '1.2.2')
    implementation(group: 'com.google.cloud', name: 'google-cloud-datastore', version: '2.1.3')
    implementation(group: 'com.google.cloud', name: 'google-cloud-storage', version: '2.1.9')
    implementation(group: 'com.google.cloud', name: 'google-cloud-pubsub', version: '1.114.7')
    implementation(group: 'com.google.cloud', name: 'google-cloud-bigquery', version: '2.3.3')
}

configurations.all {
    resolutionStrategy {
        force 'com.google.guava:guava:31.0.1-jre'
        force 'com.google.protobuf:protobuf-java:3.19.1'
        force 'com.google.api-client:google-api-client:1.32.2'
    }
}
```

*error*
```
java.lang.NoSuchMethodError: com.google.api.client.http.HttpTransport.isMtls()Z
	at com.google.api.services.storage.Storage$Builder.chooseEndpoint(Storage.java:11151)
	at com.google.api.services.storage.Storage$Builder.<init>(Storage.java:11184)
	at com.google.cloud.storage.spi.v1.HttpStorageRpc.<init>(HttpStorageRpc.java:118)
	at com.google.cloud.storage.StorageOptions$DefaultStorageRpcFactory.create(StorageOptions.java:58)
	at com.google.cloud.storage.StorageOptions$DefaultStorageRpcFactory.create(StorageOptions.java:52)
	at com.google.cloud.ServiceOptions.getRpc(ServiceOptions.java:561)
	at com.google.cloud.storage.StorageOptions.getStorageRpcV1(StorageOptions.java:146)
	at com.google.cloud.storage.StorageImpl.<init>(StorageImpl.java:115)
	at com.google.cloud.storage.StorageOptions$DefaultStorageFactory.create(StorageOptions.java:48)
	at com.google.cloud.storage.StorageOptions$DefaultStorageFactory.create(StorageOptions.java:42)
	at com.google.cloud.ServiceOptions.getService(ServiceOptions.java:541)
(GoogleStorage.java:34)
```

With the above Gradle implementation, the dependency tree looks clean with no `google-api-client` is being used. I have explicitly specified `google-api-client:1.32.1` but no happy news. It's a little frustrating due to some strange changes we're revolving round and round with no progress.

**Comment by beena-yatin-kanyal** [comment] 2021-11-02 05:06
errorlog.txt represents the dependency tree for the below.
```
dependencies {
    frameworkJars('com.myoffice.automation:APICore:1.0.0') {
        transitive = false
    }
    implementation(group: 'com.jayway.jsonpath', name: 'json-path', version: '2.0.0')
    implementation(group: 'io.jsonwebtoken', name: 'jjwt', version: '0.9.1')
    implementation(group: 'com.google.auth', name: 'google-auth-library-oauth2-http',
            version: '1.2.2')
    implementation(group: 'com.google.cloud', name: 'google-cloud-datastore', version: '2.1.3')
    implementation(group: 'com.google.cloud', name: 'google-cloud-storage', version: '2.1.9')
    implementation(group: 'com.google.cloud', name: 'google-cloud-pubsub', version: '1.114.7')
    implementation(group: 'com.google.cloud', name: 'google-cloud-bigquery', version: '2.3.3')
}

configurations.all {
    resolutionStrategy {
        force 'com.google.guava:guava:31.0.1-jre'
        force 'com.google.protobuf:protobuf-java:3.19.1'
        force 'com.google.api-client:google-api-client:1.32.2'
    }
}
```

**Comment by chanseokoh** [comment] 2021-11-02 15:24
Note the doc says

> When we publish a version of Google Cloud Platform Libraries BOM, we ensure that the libraries in the BOM do not have dependency conflicts, that would manifest as `NoSuchMethodError` or `NoClassDefFoundError`. By using the Libraries BOM, you can ensure your projects always have compatible versions of these several hundred different artifacts.

It's there to solve the exact problem you are having.

**Comment by beena-yatin-kanyal** [comment] 2021-11-02 16:44
got it @chanseokoh. let me try that and see if I can make things work now. thanks much for your help. we have a multi-module project so multiple teams work on it and it usually becomes hard to keep track of the BOM versions unless we come up with some common being derived from the parent.

**Comment by lesv** [comment] 2021-11-10 00:47
I'm going to close this since it seems solved.  If not, please feel free to reopen or ask us to do so.

**Closed by lesv** 2021-11-10 00:47 UTC
Labels: type: question, priority: p2

**Comment by beena-yatin-kanyal** [comment] 2021-11-12 15:01
@lesv - thanks. appreciate your help.
